name: OutkastMC
main: org.projectoutkast.outkastmc.OutkastMCMain
version: 0.1.0
description: Server-Side logic for the Project Outkast Minecraft Server.
author: ElPicaronCL - Sebastian Tapia
website: https://digitalxpstudios.cc
api-version: '1.21.11'