name: OutkastMC
main: org.projectoutkast.outkastmc.OutkastMC
version: 0.1.0
description: An example plugin
author: ElPicaronCL - Sebastian Tapia
website: https://digitalxpstudios.cc
api-version: '1.21.11'